// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: proto/knowledgebase-service/knowledgebase-service.proto

package knowledgebase_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowledgeBaseService_SelectKnowledgeList_FullMethodName             = "/knowledgebase_service.KnowledgeBaseService/SelectKnowledgeList"
	KnowledgeBaseService_SelectKnowledgeListByIdList_FullMethodName     = "/knowledgebase_service.KnowledgeBaseService/SelectKnowledgeListByIdList"
	KnowledgeBaseService_SelectKnowledgeDetailById_FullMethodName       = "/knowledgebase_service.KnowledgeBaseService/SelectKnowledgeDetailById"
	KnowledgeBaseService_SelectKnowledgeDetailByIdList_FullMethodName   = "/knowledgebase_service.KnowledgeBaseService/SelectKnowledgeDetailByIdList"
	KnowledgeBaseService_SelectKnowledgeDetailByName_FullMethodName     = "/knowledgebase_service.KnowledgeBaseService/SelectKnowledgeDetailByName"
	KnowledgeBaseService_SelectKnowledgeIdByRagName_FullMethodName      = "/knowledgebase_service.KnowledgeBaseService/SelectKnowledgeIdByRagName"
	KnowledgeBaseService_CreateKnowledge_FullMethodName                 = "/knowledgebase_service.KnowledgeBaseService/CreateKnowledge"
	KnowledgeBaseService_UpdateKnowledge_FullMethodName                 = "/knowledgebase_service.KnowledgeBaseService/UpdateKnowledge"
	KnowledgeBaseService_DeleteKnowledge_FullMethodName                 = "/knowledgebase_service.KnowledgeBaseService/DeleteKnowledge"
	KnowledgeBaseService_KnowledgeHit_FullMethodName                    = "/knowledgebase_service.KnowledgeBaseService/KnowledgeHit"
	KnowledgeBaseService_GetKnowledgeMetaSelect_FullMethodName          = "/knowledgebase_service.KnowledgeBaseService/GetKnowledgeMetaSelect"
	KnowledgeBaseService_GetKnowledgeMetaValueList_FullMethodName       = "/knowledgebase_service.KnowledgeBaseService/GetKnowledgeMetaValueList"
	KnowledgeBaseService_UpdateKnowledgeMetaValue_FullMethodName        = "/knowledgebase_service.KnowledgeBaseService/UpdateKnowledgeMetaValue"
	KnowledgeBaseService_UpdateKnowledgeStatus_FullMethodName           = "/knowledgebase_service.KnowledgeBaseService/UpdateKnowledgeStatus"
	KnowledgeBaseService_GetKnowledgeGraph_FullMethodName               = "/knowledgebase_service.KnowledgeBaseService/GetKnowledgeGraph"
	KnowledgeBaseService_GetExportRecordList_FullMethodName             = "/knowledgebase_service.KnowledgeBaseService/GetExportRecordList"
	KnowledgeBaseService_DeleteExportRecord_FullMethodName              = "/knowledgebase_service.KnowledgeBaseService/DeleteExportRecord"
	KnowledgeBaseService_SelectKnowledgeExternalAPIList_FullMethodName  = "/knowledgebase_service.KnowledgeBaseService/SelectKnowledgeExternalAPIList"
	KnowledgeBaseService_SelectKnowledgeExternalAPIInfo_FullMethodName  = "/knowledgebase_service.KnowledgeBaseService/SelectKnowledgeExternalAPIInfo"
	KnowledgeBaseService_CreateKnowledgeExternalAPI_FullMethodName      = "/knowledgebase_service.KnowledgeBaseService/CreateKnowledgeExternalAPI"
	KnowledgeBaseService_UpdateKnowledgeExternalAPI_FullMethodName      = "/knowledgebase_service.KnowledgeBaseService/UpdateKnowledgeExternalAPI"
	KnowledgeBaseService_DeleteKnowledgeExternalAPI_FullMethodName      = "/knowledgebase_service.KnowledgeBaseService/DeleteKnowledgeExternalAPI"
	KnowledgeBaseService_SelectKnowledgeExternalList_FullMethodName     = "/knowledgebase_service.KnowledgeBaseService/SelectKnowledgeExternalList"
	KnowledgeBaseService_SelectKnowledgeExternalInfo_FullMethodName     = "/knowledgebase_service.KnowledgeBaseService/SelectKnowledgeExternalInfo"
	KnowledgeBaseService_CreateKnowledgeExternal_FullMethodName         = "/knowledgebase_service.KnowledgeBaseService/CreateKnowledgeExternal"
	KnowledgeBaseService_UpdateKnowledgeExternal_FullMethodName         = "/knowledgebase_service.KnowledgeBaseService/UpdateKnowledgeExternal"
	KnowledgeBaseService_DeleteKnowledgeExternal_FullMethodName         = "/knowledgebase_service.KnowledgeBaseService/DeleteKnowledgeExternal"
	KnowledgeBaseService_GetDocByKnowledgeNameAndDocName_FullMethodName = "/knowledgebase_service.KnowledgeBaseService/GetDocByKnowledgeNameAndDocName"
)

// KnowledgeBaseServiceClient is the client API for KnowledgeBaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KnowledgeBaseServiceClient interface {
	// 获取知识库列表
	SelectKnowledgeList(ctx context.Context, in *KnowledgeSelectReq, opts ...grpc.CallOption) (*KnowledgeSelectListResp, error)
	// 获取知识库列表
	SelectKnowledgeListByIdList(ctx context.Context, in *BatchKnowledgeSelectReq, opts ...grpc.CallOption) (*KnowledgeSelectListResp, error)
	// 获取知识库详情
	SelectKnowledgeDetailById(ctx context.Context, in *KnowledgeDetailSelectReq, opts ...grpc.CallOption) (*KnowledgeInfo, error)
	// 获取知识库详情列表
	SelectKnowledgeDetailByIdList(ctx context.Context, in *KnowledgeDetailSelectListReq, opts ...grpc.CallOption) (*KnowledgeDetailSelectListResp, error)
	// 获取知识库详情
	SelectKnowledgeDetailByName(ctx context.Context, in *KnowledgeDetailSelectReq, opts ...grpc.CallOption) (*KnowledgeInfo, error)
	// 根据ragName获取知识库ID
	SelectKnowledgeIdByRagName(ctx context.Context, in *SelectKnowledgeIdByRagNameReq, opts ...grpc.CallOption) (*SelectKnowledgeIdByRagNameResp, error)
	// 新增知识库
	CreateKnowledge(ctx context.Context, in *CreateKnowledgeReq, opts ...grpc.CallOption) (*CreateKnowledgeResp, error)
	// 修改知识库
	UpdateKnowledge(ctx context.Context, in *UpdateKnowledgeReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除文档知识分类
	DeleteKnowledge(ctx context.Context, in *DeleteKnowledgeReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 知识库命中测试
	KnowledgeHit(ctx context.Context, in *KnowledgeHitReq, opts ...grpc.CallOption) (*KnowledgeHitResp, error)
	// 获取知识库元数据（key + type）
	GetKnowledgeMetaSelect(ctx context.Context, in *SelectKnowledgeMetaReq, opts ...grpc.CallOption) (*SelectKnowledgeMetaResp, error)
	// 获取知识库元数据值列表 (合并过的value)
	GetKnowledgeMetaValueList(ctx context.Context, in *KnowledgeMetaValueListReq, opts ...grpc.CallOption) (*KnowledgeMetaValueListResp, error)
	// 更新知识库元数据值列表
	UpdateKnowledgeMetaValue(ctx context.Context, in *UpdateKnowledgeMetaValueReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 修改知识库状态
	UpdateKnowledgeStatus(ctx context.Context, in *UpdateKnowledgeStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取知识图谱详情
	GetKnowledgeGraph(ctx context.Context, in *KnowledgeGraphReq, opts ...grpc.CallOption) (*KnowledgeGraphResp, error)
	// 获取导出记录列表
	GetExportRecordList(ctx context.Context, in *GetExportRecordListReq, opts ...grpc.CallOption) (*GetExportRecordListResp, error)
	// 删除导出记录
	DeleteExportRecord(ctx context.Context, in *DeleteExportRecordReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取外部知识库API列表
	SelectKnowledgeExternalAPIList(ctx context.Context, in *KnowledgeExternalAPIListSelectReq, opts ...grpc.CallOption) (*KnowledgeExternalAPISelectListResp, error)
	// 获取外部知识库API详情
	SelectKnowledgeExternalAPIInfo(ctx context.Context, in *KnowledgeExternalAPIInfoSelectReq, opts ...grpc.CallOption) (*KnowledgeExternalAPIInfo, error)
	// 新增外部知识库API
	CreateKnowledgeExternalAPI(ctx context.Context, in *CreateKnowledgeExternalAPIReq, opts ...grpc.CallOption) (*CreateKnowledgeExternalAPIResp, error)
	// 修改外部知识库API
	UpdateKnowledgeExternalAPI(ctx context.Context, in *UpdateKnowledgeExternalAPIReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除外部知识库API
	DeleteKnowledgeExternalAPI(ctx context.Context, in *DeleteKnowledgeExternalAPIReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取外部知识库列表
	SelectKnowledgeExternalList(ctx context.Context, in *KnowledgeExternalListSelectReq, opts ...grpc.CallOption) (*KnowledgeExternalSelectListResp, error)
	// 获取外部知识库详情
	SelectKnowledgeExternalInfo(ctx context.Context, in *KnowledgeExternalInfoSelectReq, opts ...grpc.CallOption) (*KnowledgeExternalInfo, error)
	// 新增外部知识库
	CreateKnowledgeExternal(ctx context.Context, in *CreateKnowledgeExternalReq, opts ...grpc.CallOption) (*CreateKnowledgeExternalResp, error)
	// 修改外部知识库
	UpdateKnowledgeExternal(ctx context.Context, in *UpdateKnowledgeExternalReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除外部知识库
	DeleteKnowledgeExternal(ctx context.Context, in *DeleteKnowledgeExternalReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 根据知识库名称和文档名称获取文档信息
	GetDocByKnowledgeNameAndDocName(ctx context.Context, in *GetDocByKnowledgeNameAndDocNameReq, opts ...grpc.CallOption) (*GetDocByKnowledgeNameAndDocNameResp, error)
}

type knowledgeBaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeBaseServiceClient(cc grpc.ClientConnInterface) KnowledgeBaseServiceClient {
	return &knowledgeBaseServiceClient{cc}
}

func (c *knowledgeBaseServiceClient) SelectKnowledgeList(ctx context.Context, in *KnowledgeSelectReq, opts ...grpc.CallOption) (*KnowledgeSelectListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeSelectListResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_SelectKnowledgeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) SelectKnowledgeListByIdList(ctx context.Context, in *BatchKnowledgeSelectReq, opts ...grpc.CallOption) (*KnowledgeSelectListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeSelectListResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_SelectKnowledgeListByIdList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) SelectKnowledgeDetailById(ctx context.Context, in *KnowledgeDetailSelectReq, opts ...grpc.CallOption) (*KnowledgeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeInfo)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_SelectKnowledgeDetailById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) SelectKnowledgeDetailByIdList(ctx context.Context, in *KnowledgeDetailSelectListReq, opts ...grpc.CallOption) (*KnowledgeDetailSelectListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeDetailSelectListResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_SelectKnowledgeDetailByIdList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) SelectKnowledgeDetailByName(ctx context.Context, in *KnowledgeDetailSelectReq, opts ...grpc.CallOption) (*KnowledgeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeInfo)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_SelectKnowledgeDetailByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) SelectKnowledgeIdByRagName(ctx context.Context, in *SelectKnowledgeIdByRagNameReq, opts ...grpc.CallOption) (*SelectKnowledgeIdByRagNameResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectKnowledgeIdByRagNameResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_SelectKnowledgeIdByRagName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) CreateKnowledge(ctx context.Context, in *CreateKnowledgeReq, opts ...grpc.CallOption) (*CreateKnowledgeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKnowledgeResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_CreateKnowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) UpdateKnowledge(ctx context.Context, in *UpdateKnowledgeReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_UpdateKnowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) DeleteKnowledge(ctx context.Context, in *DeleteKnowledgeReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_DeleteKnowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) KnowledgeHit(ctx context.Context, in *KnowledgeHitReq, opts ...grpc.CallOption) (*KnowledgeHitResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeHitResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_KnowledgeHit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) GetKnowledgeMetaSelect(ctx context.Context, in *SelectKnowledgeMetaReq, opts ...grpc.CallOption) (*SelectKnowledgeMetaResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectKnowledgeMetaResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_GetKnowledgeMetaSelect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) GetKnowledgeMetaValueList(ctx context.Context, in *KnowledgeMetaValueListReq, opts ...grpc.CallOption) (*KnowledgeMetaValueListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeMetaValueListResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_GetKnowledgeMetaValueList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) UpdateKnowledgeMetaValue(ctx context.Context, in *UpdateKnowledgeMetaValueReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_UpdateKnowledgeMetaValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) UpdateKnowledgeStatus(ctx context.Context, in *UpdateKnowledgeStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_UpdateKnowledgeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) GetKnowledgeGraph(ctx context.Context, in *KnowledgeGraphReq, opts ...grpc.CallOption) (*KnowledgeGraphResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeGraphResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_GetKnowledgeGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) GetExportRecordList(ctx context.Context, in *GetExportRecordListReq, opts ...grpc.CallOption) (*GetExportRecordListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExportRecordListResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_GetExportRecordList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) DeleteExportRecord(ctx context.Context, in *DeleteExportRecordReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_DeleteExportRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) SelectKnowledgeExternalAPIList(ctx context.Context, in *KnowledgeExternalAPIListSelectReq, opts ...grpc.CallOption) (*KnowledgeExternalAPISelectListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeExternalAPISelectListResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_SelectKnowledgeExternalAPIList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) SelectKnowledgeExternalAPIInfo(ctx context.Context, in *KnowledgeExternalAPIInfoSelectReq, opts ...grpc.CallOption) (*KnowledgeExternalAPIInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeExternalAPIInfo)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_SelectKnowledgeExternalAPIInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) CreateKnowledgeExternalAPI(ctx context.Context, in *CreateKnowledgeExternalAPIReq, opts ...grpc.CallOption) (*CreateKnowledgeExternalAPIResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKnowledgeExternalAPIResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_CreateKnowledgeExternalAPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) UpdateKnowledgeExternalAPI(ctx context.Context, in *UpdateKnowledgeExternalAPIReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_UpdateKnowledgeExternalAPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) DeleteKnowledgeExternalAPI(ctx context.Context, in *DeleteKnowledgeExternalAPIReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_DeleteKnowledgeExternalAPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) SelectKnowledgeExternalList(ctx context.Context, in *KnowledgeExternalListSelectReq, opts ...grpc.CallOption) (*KnowledgeExternalSelectListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeExternalSelectListResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_SelectKnowledgeExternalList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) SelectKnowledgeExternalInfo(ctx context.Context, in *KnowledgeExternalInfoSelectReq, opts ...grpc.CallOption) (*KnowledgeExternalInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeExternalInfo)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_SelectKnowledgeExternalInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) CreateKnowledgeExternal(ctx context.Context, in *CreateKnowledgeExternalReq, opts ...grpc.CallOption) (*CreateKnowledgeExternalResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKnowledgeExternalResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_CreateKnowledgeExternal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) UpdateKnowledgeExternal(ctx context.Context, in *UpdateKnowledgeExternalReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_UpdateKnowledgeExternal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) DeleteKnowledgeExternal(ctx context.Context, in *DeleteKnowledgeExternalReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_DeleteKnowledgeExternal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseServiceClient) GetDocByKnowledgeNameAndDocName(ctx context.Context, in *GetDocByKnowledgeNameAndDocNameReq, opts ...grpc.CallOption) (*GetDocByKnowledgeNameAndDocNameResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocByKnowledgeNameAndDocNameResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseService_GetDocByKnowledgeNameAndDocName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeBaseServiceServer is the server API for KnowledgeBaseService service.
// All implementations must embed UnimplementedKnowledgeBaseServiceServer
// for forward compatibility.
type KnowledgeBaseServiceServer interface {
	// 获取知识库列表
	SelectKnowledgeList(context.Context, *KnowledgeSelectReq) (*KnowledgeSelectListResp, error)
	// 获取知识库列表
	SelectKnowledgeListByIdList(context.Context, *BatchKnowledgeSelectReq) (*KnowledgeSelectListResp, error)
	// 获取知识库详情
	SelectKnowledgeDetailById(context.Context, *KnowledgeDetailSelectReq) (*KnowledgeInfo, error)
	// 获取知识库详情列表
	SelectKnowledgeDetailByIdList(context.Context, *KnowledgeDetailSelectListReq) (*KnowledgeDetailSelectListResp, error)
	// 获取知识库详情
	SelectKnowledgeDetailByName(context.Context, *KnowledgeDetailSelectReq) (*KnowledgeInfo, error)
	// 根据ragName获取知识库ID
	SelectKnowledgeIdByRagName(context.Context, *SelectKnowledgeIdByRagNameReq) (*SelectKnowledgeIdByRagNameResp, error)
	// 新增知识库
	CreateKnowledge(context.Context, *CreateKnowledgeReq) (*CreateKnowledgeResp, error)
	// 修改知识库
	UpdateKnowledge(context.Context, *UpdateKnowledgeReq) (*emptypb.Empty, error)
	// 删除文档知识分类
	DeleteKnowledge(context.Context, *DeleteKnowledgeReq) (*emptypb.Empty, error)
	// 知识库命中测试
	KnowledgeHit(context.Context, *KnowledgeHitReq) (*KnowledgeHitResp, error)
	// 获取知识库元数据（key + type）
	GetKnowledgeMetaSelect(context.Context, *SelectKnowledgeMetaReq) (*SelectKnowledgeMetaResp, error)
	// 获取知识库元数据值列表 (合并过的value)
	GetKnowledgeMetaValueList(context.Context, *KnowledgeMetaValueListReq) (*KnowledgeMetaValueListResp, error)
	// 更新知识库元数据值列表
	UpdateKnowledgeMetaValue(context.Context, *UpdateKnowledgeMetaValueReq) (*emptypb.Empty, error)
	// 修改知识库状态
	UpdateKnowledgeStatus(context.Context, *UpdateKnowledgeStatusReq) (*emptypb.Empty, error)
	// 获取知识图谱详情
	GetKnowledgeGraph(context.Context, *KnowledgeGraphReq) (*KnowledgeGraphResp, error)
	// 获取导出记录列表
	GetExportRecordList(context.Context, *GetExportRecordListReq) (*GetExportRecordListResp, error)
	// 删除导出记录
	DeleteExportRecord(context.Context, *DeleteExportRecordReq) (*emptypb.Empty, error)
	// 获取外部知识库API列表
	SelectKnowledgeExternalAPIList(context.Context, *KnowledgeExternalAPIListSelectReq) (*KnowledgeExternalAPISelectListResp, error)
	// 获取外部知识库API详情
	SelectKnowledgeExternalAPIInfo(context.Context, *KnowledgeExternalAPIInfoSelectReq) (*KnowledgeExternalAPIInfo, error)
	// 新增外部知识库API
	CreateKnowledgeExternalAPI(context.Context, *CreateKnowledgeExternalAPIReq) (*CreateKnowledgeExternalAPIResp, error)
	// 修改外部知识库API
	UpdateKnowledgeExternalAPI(context.Context, *UpdateKnowledgeExternalAPIReq) (*emptypb.Empty, error)
	// 删除外部知识库API
	DeleteKnowledgeExternalAPI(context.Context, *DeleteKnowledgeExternalAPIReq) (*emptypb.Empty, error)
	// 获取外部知识库列表
	SelectKnowledgeExternalList(context.Context, *KnowledgeExternalListSelectReq) (*KnowledgeExternalSelectListResp, error)
	// 获取外部知识库详情
	SelectKnowledgeExternalInfo(context.Context, *KnowledgeExternalInfoSelectReq) (*KnowledgeExternalInfo, error)
	// 新增外部知识库
	CreateKnowledgeExternal(context.Context, *CreateKnowledgeExternalReq) (*CreateKnowledgeExternalResp, error)
	// 修改外部知识库
	UpdateKnowledgeExternal(context.Context, *UpdateKnowledgeExternalReq) (*emptypb.Empty, error)
	// 删除外部知识库
	DeleteKnowledgeExternal(context.Context, *DeleteKnowledgeExternalReq) (*emptypb.Empty, error)
	// 根据知识库名称和文档名称获取文档信息
	GetDocByKnowledgeNameAndDocName(context.Context, *GetDocByKnowledgeNameAndDocNameReq) (*GetDocByKnowledgeNameAndDocNameResp, error)
	mustEmbedUnimplementedKnowledgeBaseServiceServer()
}

// UnimplementedKnowledgeBaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeBaseServiceServer struct{}

func (UnimplementedKnowledgeBaseServiceServer) SelectKnowledgeList(context.Context, *KnowledgeSelectReq) (*KnowledgeSelectListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectKnowledgeList not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) SelectKnowledgeListByIdList(context.Context, *BatchKnowledgeSelectReq) (*KnowledgeSelectListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectKnowledgeListByIdList not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) SelectKnowledgeDetailById(context.Context, *KnowledgeDetailSelectReq) (*KnowledgeInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectKnowledgeDetailById not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) SelectKnowledgeDetailByIdList(context.Context, *KnowledgeDetailSelectListReq) (*KnowledgeDetailSelectListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectKnowledgeDetailByIdList not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) SelectKnowledgeDetailByName(context.Context, *KnowledgeDetailSelectReq) (*KnowledgeInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectKnowledgeDetailByName not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) SelectKnowledgeIdByRagName(context.Context, *SelectKnowledgeIdByRagNameReq) (*SelectKnowledgeIdByRagNameResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectKnowledgeIdByRagName not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) CreateKnowledge(context.Context, *CreateKnowledgeReq) (*CreateKnowledgeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKnowledge not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) UpdateKnowledge(context.Context, *UpdateKnowledgeReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKnowledge not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) DeleteKnowledge(context.Context, *DeleteKnowledgeReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKnowledge not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) KnowledgeHit(context.Context, *KnowledgeHitReq) (*KnowledgeHitResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KnowledgeHit not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) GetKnowledgeMetaSelect(context.Context, *SelectKnowledgeMetaReq) (*SelectKnowledgeMetaResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKnowledgeMetaSelect not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) GetKnowledgeMetaValueList(context.Context, *KnowledgeMetaValueListReq) (*KnowledgeMetaValueListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKnowledgeMetaValueList not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) UpdateKnowledgeMetaValue(context.Context, *UpdateKnowledgeMetaValueReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKnowledgeMetaValue not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) UpdateKnowledgeStatus(context.Context, *UpdateKnowledgeStatusReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKnowledgeStatus not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) GetKnowledgeGraph(context.Context, *KnowledgeGraphReq) (*KnowledgeGraphResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKnowledgeGraph not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) GetExportRecordList(context.Context, *GetExportRecordListReq) (*GetExportRecordListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExportRecordList not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) DeleteExportRecord(context.Context, *DeleteExportRecordReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExportRecord not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) SelectKnowledgeExternalAPIList(context.Context, *KnowledgeExternalAPIListSelectReq) (*KnowledgeExternalAPISelectListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectKnowledgeExternalAPIList not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) SelectKnowledgeExternalAPIInfo(context.Context, *KnowledgeExternalAPIInfoSelectReq) (*KnowledgeExternalAPIInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectKnowledgeExternalAPIInfo not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) CreateKnowledgeExternalAPI(context.Context, *CreateKnowledgeExternalAPIReq) (*CreateKnowledgeExternalAPIResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKnowledgeExternalAPI not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) UpdateKnowledgeExternalAPI(context.Context, *UpdateKnowledgeExternalAPIReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKnowledgeExternalAPI not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) DeleteKnowledgeExternalAPI(context.Context, *DeleteKnowledgeExternalAPIReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKnowledgeExternalAPI not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) SelectKnowledgeExternalList(context.Context, *KnowledgeExternalListSelectReq) (*KnowledgeExternalSelectListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectKnowledgeExternalList not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) SelectKnowledgeExternalInfo(context.Context, *KnowledgeExternalInfoSelectReq) (*KnowledgeExternalInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectKnowledgeExternalInfo not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) CreateKnowledgeExternal(context.Context, *CreateKnowledgeExternalReq) (*CreateKnowledgeExternalResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKnowledgeExternal not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) UpdateKnowledgeExternal(context.Context, *UpdateKnowledgeExternalReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKnowledgeExternal not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) DeleteKnowledgeExternal(context.Context, *DeleteKnowledgeExternalReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKnowledgeExternal not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) GetDocByKnowledgeNameAndDocName(context.Context, *GetDocByKnowledgeNameAndDocNameReq) (*GetDocByKnowledgeNameAndDocNameResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocByKnowledgeNameAndDocName not implemented")
}
func (UnimplementedKnowledgeBaseServiceServer) mustEmbedUnimplementedKnowledgeBaseServiceServer() {}
func (UnimplementedKnowledgeBaseServiceServer) testEmbeddedByValue()                              {}

// UnsafeKnowledgeBaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeBaseServiceServer will
// result in compilation errors.
type UnsafeKnowledgeBaseServiceServer interface {
	mustEmbedUnimplementedKnowledgeBaseServiceServer()
}

func RegisterKnowledgeBaseServiceServer(s grpc.ServiceRegistrar, srv KnowledgeBaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedKnowledgeBaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeBaseService_ServiceDesc, srv)
}

func _KnowledgeBaseService_SelectKnowledgeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeSelectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_SelectKnowledgeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeList(ctx, req.(*KnowledgeSelectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_SelectKnowledgeListByIdList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchKnowledgeSelectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeListByIdList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_SelectKnowledgeListByIdList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeListByIdList(ctx, req.(*BatchKnowledgeSelectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_SelectKnowledgeDetailById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeDetailSelectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeDetailById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_SelectKnowledgeDetailById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeDetailById(ctx, req.(*KnowledgeDetailSelectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_SelectKnowledgeDetailByIdList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeDetailSelectListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeDetailByIdList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_SelectKnowledgeDetailByIdList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeDetailByIdList(ctx, req.(*KnowledgeDetailSelectListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_SelectKnowledgeDetailByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeDetailSelectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeDetailByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_SelectKnowledgeDetailByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeDetailByName(ctx, req.(*KnowledgeDetailSelectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_SelectKnowledgeIdByRagName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectKnowledgeIdByRagNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeIdByRagName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_SelectKnowledgeIdByRagName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeIdByRagName(ctx, req.(*SelectKnowledgeIdByRagNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_CreateKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKnowledgeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).CreateKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_CreateKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).CreateKnowledge(ctx, req.(*CreateKnowledgeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_UpdateKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKnowledgeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).UpdateKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_UpdateKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).UpdateKnowledge(ctx, req.(*UpdateKnowledgeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_DeleteKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKnowledgeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).DeleteKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_DeleteKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).DeleteKnowledge(ctx, req.(*DeleteKnowledgeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_KnowledgeHit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeHitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).KnowledgeHit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_KnowledgeHit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).KnowledgeHit(ctx, req.(*KnowledgeHitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_GetKnowledgeMetaSelect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectKnowledgeMetaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).GetKnowledgeMetaSelect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_GetKnowledgeMetaSelect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).GetKnowledgeMetaSelect(ctx, req.(*SelectKnowledgeMetaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_GetKnowledgeMetaValueList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeMetaValueListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).GetKnowledgeMetaValueList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_GetKnowledgeMetaValueList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).GetKnowledgeMetaValueList(ctx, req.(*KnowledgeMetaValueListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_UpdateKnowledgeMetaValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKnowledgeMetaValueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).UpdateKnowledgeMetaValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_UpdateKnowledgeMetaValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).UpdateKnowledgeMetaValue(ctx, req.(*UpdateKnowledgeMetaValueReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_UpdateKnowledgeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKnowledgeStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).UpdateKnowledgeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_UpdateKnowledgeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).UpdateKnowledgeStatus(ctx, req.(*UpdateKnowledgeStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_GetKnowledgeGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeGraphReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).GetKnowledgeGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_GetKnowledgeGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).GetKnowledgeGraph(ctx, req.(*KnowledgeGraphReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_GetExportRecordList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExportRecordListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).GetExportRecordList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_GetExportRecordList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).GetExportRecordList(ctx, req.(*GetExportRecordListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_DeleteExportRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExportRecordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).DeleteExportRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_DeleteExportRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).DeleteExportRecord(ctx, req.(*DeleteExportRecordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_SelectKnowledgeExternalAPIList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeExternalAPIListSelectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeExternalAPIList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_SelectKnowledgeExternalAPIList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeExternalAPIList(ctx, req.(*KnowledgeExternalAPIListSelectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_SelectKnowledgeExternalAPIInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeExternalAPIInfoSelectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeExternalAPIInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_SelectKnowledgeExternalAPIInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeExternalAPIInfo(ctx, req.(*KnowledgeExternalAPIInfoSelectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_CreateKnowledgeExternalAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKnowledgeExternalAPIReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).CreateKnowledgeExternalAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_CreateKnowledgeExternalAPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).CreateKnowledgeExternalAPI(ctx, req.(*CreateKnowledgeExternalAPIReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_UpdateKnowledgeExternalAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKnowledgeExternalAPIReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).UpdateKnowledgeExternalAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_UpdateKnowledgeExternalAPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).UpdateKnowledgeExternalAPI(ctx, req.(*UpdateKnowledgeExternalAPIReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_DeleteKnowledgeExternalAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKnowledgeExternalAPIReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).DeleteKnowledgeExternalAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_DeleteKnowledgeExternalAPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).DeleteKnowledgeExternalAPI(ctx, req.(*DeleteKnowledgeExternalAPIReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_SelectKnowledgeExternalList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeExternalListSelectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeExternalList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_SelectKnowledgeExternalList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeExternalList(ctx, req.(*KnowledgeExternalListSelectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_SelectKnowledgeExternalInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeExternalInfoSelectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeExternalInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_SelectKnowledgeExternalInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).SelectKnowledgeExternalInfo(ctx, req.(*KnowledgeExternalInfoSelectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_CreateKnowledgeExternal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKnowledgeExternalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).CreateKnowledgeExternal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_CreateKnowledgeExternal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).CreateKnowledgeExternal(ctx, req.(*CreateKnowledgeExternalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_UpdateKnowledgeExternal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKnowledgeExternalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).UpdateKnowledgeExternal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_UpdateKnowledgeExternal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).UpdateKnowledgeExternal(ctx, req.(*UpdateKnowledgeExternalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_DeleteKnowledgeExternal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKnowledgeExternalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).DeleteKnowledgeExternal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_DeleteKnowledgeExternal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).DeleteKnowledgeExternal(ctx, req.(*DeleteKnowledgeExternalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseService_GetDocByKnowledgeNameAndDocName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocByKnowledgeNameAndDocNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseServiceServer).GetDocByKnowledgeNameAndDocName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseService_GetDocByKnowledgeNameAndDocName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseServiceServer).GetDocByKnowledgeNameAndDocName(ctx, req.(*GetDocByKnowledgeNameAndDocNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeBaseService_ServiceDesc is the grpc.ServiceDesc for KnowledgeBaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeBaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knowledgebase_service.KnowledgeBaseService",
	HandlerType: (*KnowledgeBaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectKnowledgeList",
			Handler:    _KnowledgeBaseService_SelectKnowledgeList_Handler,
		},
		{
			MethodName: "SelectKnowledgeListByIdList",
			Handler:    _KnowledgeBaseService_SelectKnowledgeListByIdList_Handler,
		},
		{
			MethodName: "SelectKnowledgeDetailById",
			Handler:    _KnowledgeBaseService_SelectKnowledgeDetailById_Handler,
		},
		{
			MethodName: "SelectKnowledgeDetailByIdList",
			Handler:    _KnowledgeBaseService_SelectKnowledgeDetailByIdList_Handler,
		},
		{
			MethodName: "SelectKnowledgeDetailByName",
			Handler:    _KnowledgeBaseService_SelectKnowledgeDetailByName_Handler,
		},
		{
			MethodName: "SelectKnowledgeIdByRagName",
			Handler:    _KnowledgeBaseService_SelectKnowledgeIdByRagName_Handler,
		},
		{
			MethodName: "CreateKnowledge",
			Handler:    _KnowledgeBaseService_CreateKnowledge_Handler,
		},
		{
			MethodName: "UpdateKnowledge",
			Handler:    _KnowledgeBaseService_UpdateKnowledge_Handler,
		},
		{
			MethodName: "DeleteKnowledge",
			Handler:    _KnowledgeBaseService_DeleteKnowledge_Handler,
		},
		{
			MethodName: "KnowledgeHit",
			Handler:    _KnowledgeBaseService_KnowledgeHit_Handler,
		},
		{
			MethodName: "GetKnowledgeMetaSelect",
			Handler:    _KnowledgeBaseService_GetKnowledgeMetaSelect_Handler,
		},
		{
			MethodName: "GetKnowledgeMetaValueList",
			Handler:    _KnowledgeBaseService_GetKnowledgeMetaValueList_Handler,
		},
		{
			MethodName: "UpdateKnowledgeMetaValue",
			Handler:    _KnowledgeBaseService_UpdateKnowledgeMetaValue_Handler,
		},
		{
			MethodName: "UpdateKnowledgeStatus",
			Handler:    _KnowledgeBaseService_UpdateKnowledgeStatus_Handler,
		},
		{
			MethodName: "GetKnowledgeGraph",
			Handler:    _KnowledgeBaseService_GetKnowledgeGraph_Handler,
		},
		{
			MethodName: "GetExportRecordList",
			Handler:    _KnowledgeBaseService_GetExportRecordList_Handler,
		},
		{
			MethodName: "DeleteExportRecord",
			Handler:    _KnowledgeBaseService_DeleteExportRecord_Handler,
		},
		{
			MethodName: "SelectKnowledgeExternalAPIList",
			Handler:    _KnowledgeBaseService_SelectKnowledgeExternalAPIList_Handler,
		},
		{
			MethodName: "SelectKnowledgeExternalAPIInfo",
			Handler:    _KnowledgeBaseService_SelectKnowledgeExternalAPIInfo_Handler,
		},
		{
			MethodName: "CreateKnowledgeExternalAPI",
			Handler:    _KnowledgeBaseService_CreateKnowledgeExternalAPI_Handler,
		},
		{
			MethodName: "UpdateKnowledgeExternalAPI",
			Handler:    _KnowledgeBaseService_UpdateKnowledgeExternalAPI_Handler,
		},
		{
			MethodName: "DeleteKnowledgeExternalAPI",
			Handler:    _KnowledgeBaseService_DeleteKnowledgeExternalAPI_Handler,
		},
		{
			MethodName: "SelectKnowledgeExternalList",
			Handler:    _KnowledgeBaseService_SelectKnowledgeExternalList_Handler,
		},
		{
			MethodName: "SelectKnowledgeExternalInfo",
			Handler:    _KnowledgeBaseService_SelectKnowledgeExternalInfo_Handler,
		},
		{
			MethodName: "CreateKnowledgeExternal",
			Handler:    _KnowledgeBaseService_CreateKnowledgeExternal_Handler,
		},
		{
			MethodName: "UpdateKnowledgeExternal",
			Handler:    _KnowledgeBaseService_UpdateKnowledgeExternal_Handler,
		},
		{
			MethodName: "DeleteKnowledgeExternal",
			Handler:    _KnowledgeBaseService_DeleteKnowledgeExternal_Handler,
		},
		{
			MethodName: "GetDocByKnowledgeNameAndDocName",
			Handler:    _KnowledgeBaseService_GetDocByKnowledgeNameAndDocName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/knowledgebase-service/knowledgebase-service.proto",
}
