# --- 第一阶段：构建阶段aibase ---
FROM node:22 AS builder-aibase
WORKDIR /app
COPY wanwu/web .

# ENV npm_config_registry=https://registry.npmjs.com
ENV npm_config_registry=https://registry.npmmirror.com
ENV npm_config_unsafe_perm=true

ENV CI=true

RUN npm install -g pnpm@10

RUN set -euo && \
pnpm install && \
pnpm run build

# --- 第二阶段：构建阶段workflow ---
FROM node:22 AS builder-workflow
WORKDIR /app
COPY wanwu-workflow .

# ENV npm_config_registry=https://registry.npmjs.com
ENV npm_config_registry=https://registry.npmmirror.com

RUN cd /app/frontend && npm install -g @microsoft/rush && rush install && rush update
RUN cd /app/frontend/apps/coze-studio && npm run build

# --- 第三阶段：运行阶段 ---
FROM nginx:1.27

COPY wanwu/configs/middleware/nginx/conf.d /etc/nginx/conf.d

COPY --from=builder-aibase /app/dist /usr/share/nginx/html/aibase

COPY --from=builder-workflow /app/frontend/apps/coze-studio/dist /usr/share/nginx/html/workflow

CMD ["nginx", "-g", "daemon off;"]