// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: proto/channel-service/channel-service.proto

package channel_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChannelService_ListWanwuAgents_FullMethodName        = "/channel_service.ChannelService/ListWanwuAgents"
	ChannelService_ListWanwuApiKeys_FullMethodName       = "/channel_service.ChannelService/ListWanwuApiKeys"
	ChannelService_CreateQRLogin_FullMethodName          = "/channel_service.ChannelService/CreateQRLogin"
	ChannelService_GetQRLoginStatus_FullMethodName       = "/channel_service.ChannelService/GetQRLoginStatus"
	ChannelService_CancelQRLogin_FullMethodName          = "/channel_service.ChannelService/CancelQRLogin"
	ChannelService_CompleteQRLogin_FullMethodName        = "/channel_service.ChannelService/CompleteQRLogin"
	ChannelService_CreateChannel_FullMethodName          = "/channel_service.ChannelService/CreateChannel"
	ChannelService_ListChannels_FullMethodName           = "/channel_service.ChannelService/ListChannels"
	ChannelService_GetChannel_FullMethodName             = "/channel_service.ChannelService/GetChannel"
	ChannelService_UpdateChannel_FullMethodName          = "/channel_service.ChannelService/UpdateChannel"
	ChannelService_UpdateChannelStatus_FullMethodName    = "/channel_service.ChannelService/UpdateChannelStatus"
	ChannelService_DeleteChannel_FullMethodName          = "/channel_service.ChannelService/DeleteChannel"
	ChannelService_DisconnectChannel_FullMethodName      = "/channel_service.ChannelService/DisconnectChannel"
	ChannelService_SendTestMessage_FullMethodName        = "/channel_service.ChannelService/SendTestMessage"
	ChannelService_GetChannelConnectivity_FullMethodName = "/channel_service.ChannelService/GetChannelConnectivity"
	ChannelService_SendMessage_FullMethodName            = "/channel_service.ChannelService/SendMessage"
)

// ChannelServiceClient is the client API for ChannelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChannelServiceClient interface {
	// --- 万悟平台代理 ---
	// 获取万悟智能体列表（前端下拉选择用）
	ListWanwuAgents(ctx context.Context, in *ListWanwuAgentsReq, opts ...grpc.CallOption) (*ListWanwuAgentsResp, error)
	// 获取万悟 API Key 列表（前端下拉选择用）
	ListWanwuApiKeys(ctx context.Context, in *ListWanwuApiKeysReq, opts ...grpc.CallOption) (*ListWanwuApiKeysResp, error)
	// --- 扫码登录 ---
	// 发起扫码登录
	CreateQRLogin(ctx context.Context, in *CreateQRLoginReq, opts ...grpc.CallOption) (*CreateQRLoginResp, error)
	// 查询扫码状态
	GetQRLoginStatus(ctx context.Context, in *GetQRLoginStatusReq, opts ...grpc.CallOption) (*QRLoginStatus, error)
	// 取消扫码登录
	CancelQRLogin(ctx context.Context, in *CancelQRLoginReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 完成扫码登录（扫码成功后创建通道）
	CompleteQRLogin(ctx context.Context, in *CompleteQRLoginReq, opts ...grpc.CallOption) (*Channel, error)
	// --- 通道管理 ---
	// 创建通道
	CreateChannel(ctx context.Context, in *CreateChannelReq, opts ...grpc.CallOption) (*Channel, error)
	// 获取通道列表
	ListChannels(ctx context.Context, in *ListChannelsReq, opts ...grpc.CallOption) (*ListChannelsResp, error)
	// 获取通道详情
	GetChannel(ctx context.Context, in *GetChannelReq, opts ...grpc.CallOption) (*Channel, error)
	// 更新通道
	UpdateChannel(ctx context.Context, in *UpdateChannelReq, opts ...grpc.CallOption) (*Channel, error)
	// 启用/停用通道
	UpdateChannelStatus(ctx context.Context, in *UpdateChannelStatusReq, opts ...grpc.CallOption) (*Channel, error)
	// 删除通道
	DeleteChannel(ctx context.Context, in *DeleteChannelReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 断开通道连接
	DisconnectChannel(ctx context.Context, in *DisconnectChannelReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// --- 通道连通性 / 测试消息 ---
	// 发送测试消息：给指定通道的收件人发一条消息，验证通道出站可用并预置会话映射。
	// 既用于建通道后自检连通性，也用于"建通道后给通道发消息"的首次投递。
	SendTestMessage(ctx context.Context, in *SendTestMessageReq, opts ...grpc.CallOption) (*SendTestMessageResp, error)
	// 查询通道实时连通状态（从适配器内存读，非 DB 快照），供前端展示 / 推送前自检。
	GetChannelConnectivity(ctx context.Context, in *GetChannelConnectivityReq, opts ...grpc.CallOption) (*Connectivity, error)
	// --- 内部服务发消息 ---
	// 供内部服务（经 bff callback）给指定通道发消息。无权限校验、不预置会话映射，
	// 仅做出站投递。user_id 不传时自动取该通道最近互动过的 IM 用户作为收件人。
	// msg_type 支持 text/markdown/file：file 时传 file_url（minio 下载地址）+ file_name，
	// channel-service 下载字节后经适配器 SendFile 投递（钉钉/微信支持，飞书不支持返回错误）。
	SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error)
}

type channelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelServiceClient(cc grpc.ClientConnInterface) ChannelServiceClient {
	return &channelServiceClient{cc}
}

func (c *channelServiceClient) ListWanwuAgents(ctx context.Context, in *ListWanwuAgentsReq, opts ...grpc.CallOption) (*ListWanwuAgentsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWanwuAgentsResp)
	err := c.cc.Invoke(ctx, ChannelService_ListWanwuAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) ListWanwuApiKeys(ctx context.Context, in *ListWanwuApiKeysReq, opts ...grpc.CallOption) (*ListWanwuApiKeysResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWanwuApiKeysResp)
	err := c.cc.Invoke(ctx, ChannelService_ListWanwuApiKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) CreateQRLogin(ctx context.Context, in *CreateQRLoginReq, opts ...grpc.CallOption) (*CreateQRLoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateQRLoginResp)
	err := c.cc.Invoke(ctx, ChannelService_CreateQRLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) GetQRLoginStatus(ctx context.Context, in *GetQRLoginStatusReq, opts ...grpc.CallOption) (*QRLoginStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QRLoginStatus)
	err := c.cc.Invoke(ctx, ChannelService_GetQRLoginStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) CancelQRLogin(ctx context.Context, in *CancelQRLoginReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChannelService_CancelQRLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) CompleteQRLogin(ctx context.Context, in *CompleteQRLoginReq, opts ...grpc.CallOption) (*Channel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Channel)
	err := c.cc.Invoke(ctx, ChannelService_CompleteQRLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) CreateChannel(ctx context.Context, in *CreateChannelReq, opts ...grpc.CallOption) (*Channel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Channel)
	err := c.cc.Invoke(ctx, ChannelService_CreateChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) ListChannels(ctx context.Context, in *ListChannelsReq, opts ...grpc.CallOption) (*ListChannelsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChannelsResp)
	err := c.cc.Invoke(ctx, ChannelService_ListChannels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) GetChannel(ctx context.Context, in *GetChannelReq, opts ...grpc.CallOption) (*Channel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Channel)
	err := c.cc.Invoke(ctx, ChannelService_GetChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) UpdateChannel(ctx context.Context, in *UpdateChannelReq, opts ...grpc.CallOption) (*Channel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Channel)
	err := c.cc.Invoke(ctx, ChannelService_UpdateChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) UpdateChannelStatus(ctx context.Context, in *UpdateChannelStatusReq, opts ...grpc.CallOption) (*Channel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Channel)
	err := c.cc.Invoke(ctx, ChannelService_UpdateChannelStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) DeleteChannel(ctx context.Context, in *DeleteChannelReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChannelService_DeleteChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) DisconnectChannel(ctx context.Context, in *DisconnectChannelReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChannelService_DisconnectChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) SendTestMessage(ctx context.Context, in *SendTestMessageReq, opts ...grpc.CallOption) (*SendTestMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendTestMessageResp)
	err := c.cc.Invoke(ctx, ChannelService_SendTestMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) GetChannelConnectivity(ctx context.Context, in *GetChannelConnectivityReq, opts ...grpc.CallOption) (*Connectivity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Connectivity)
	err := c.cc.Invoke(ctx, ChannelService_GetChannelConnectivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelServiceClient) SendMessage(ctx context.Context, in *SendMessageReq, opts ...grpc.CallOption) (*SendMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResp)
	err := c.cc.Invoke(ctx, ChannelService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelServiceServer is the server API for ChannelService service.
// All implementations must embed UnimplementedChannelServiceServer
// for forward compatibility.
type ChannelServiceServer interface {
	// --- 万悟平台代理 ---
	// 获取万悟智能体列表（前端下拉选择用）
	ListWanwuAgents(context.Context, *ListWanwuAgentsReq) (*ListWanwuAgentsResp, error)
	// 获取万悟 API Key 列表（前端下拉选择用）
	ListWanwuApiKeys(context.Context, *ListWanwuApiKeysReq) (*ListWanwuApiKeysResp, error)
	// --- 扫码登录 ---
	// 发起扫码登录
	CreateQRLogin(context.Context, *CreateQRLoginReq) (*CreateQRLoginResp, error)
	// 查询扫码状态
	GetQRLoginStatus(context.Context, *GetQRLoginStatusReq) (*QRLoginStatus, error)
	// 取消扫码登录
	CancelQRLogin(context.Context, *CancelQRLoginReq) (*emptypb.Empty, error)
	// 完成扫码登录（扫码成功后创建通道）
	CompleteQRLogin(context.Context, *CompleteQRLoginReq) (*Channel, error)
	// --- 通道管理 ---
	// 创建通道
	CreateChannel(context.Context, *CreateChannelReq) (*Channel, error)
	// 获取通道列表
	ListChannels(context.Context, *ListChannelsReq) (*ListChannelsResp, error)
	// 获取通道详情
	GetChannel(context.Context, *GetChannelReq) (*Channel, error)
	// 更新通道
	UpdateChannel(context.Context, *UpdateChannelReq) (*Channel, error)
	// 启用/停用通道
	UpdateChannelStatus(context.Context, *UpdateChannelStatusReq) (*Channel, error)
	// 删除通道
	DeleteChannel(context.Context, *DeleteChannelReq) (*emptypb.Empty, error)
	// 断开通道连接
	DisconnectChannel(context.Context, *DisconnectChannelReq) (*emptypb.Empty, error)
	// --- 通道连通性 / 测试消息 ---
	// 发送测试消息：给指定通道的收件人发一条消息，验证通道出站可用并预置会话映射。
	// 既用于建通道后自检连通性，也用于"建通道后给通道发消息"的首次投递。
	SendTestMessage(context.Context, *SendTestMessageReq) (*SendTestMessageResp, error)
	// 查询通道实时连通状态（从适配器内存读，非 DB 快照），供前端展示 / 推送前自检。
	GetChannelConnectivity(context.Context, *GetChannelConnectivityReq) (*Connectivity, error)
	// --- 内部服务发消息 ---
	// 供内部服务（经 bff callback）给指定通道发消息。无权限校验、不预置会话映射，
	// 仅做出站投递。user_id 不传时自动取该通道最近互动过的 IM 用户作为收件人。
	// msg_type 支持 text/markdown/file：file 时传 file_url（minio 下载地址）+ file_name，
	// channel-service 下载字节后经适配器 SendFile 投递（钉钉/微信支持，飞书不支持返回错误）。
	SendMessage(context.Context, *SendMessageReq) (*SendMessageResp, error)
	mustEmbedUnimplementedChannelServiceServer()
}

// UnimplementedChannelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChannelServiceServer struct{}

func (UnimplementedChannelServiceServer) ListWanwuAgents(context.Context, *ListWanwuAgentsReq) (*ListWanwuAgentsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWanwuAgents not implemented")
}
func (UnimplementedChannelServiceServer) ListWanwuApiKeys(context.Context, *ListWanwuApiKeysReq) (*ListWanwuApiKeysResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWanwuApiKeys not implemented")
}
func (UnimplementedChannelServiceServer) CreateQRLogin(context.Context, *CreateQRLoginReq) (*CreateQRLoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQRLogin not implemented")
}
func (UnimplementedChannelServiceServer) GetQRLoginStatus(context.Context, *GetQRLoginStatusReq) (*QRLoginStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQRLoginStatus not implemented")
}
func (UnimplementedChannelServiceServer) CancelQRLogin(context.Context, *CancelQRLoginReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelQRLogin not implemented")
}
func (UnimplementedChannelServiceServer) CompleteQRLogin(context.Context, *CompleteQRLoginReq) (*Channel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteQRLogin not implemented")
}
func (UnimplementedChannelServiceServer) CreateChannel(context.Context, *CreateChannelReq) (*Channel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChannel not implemented")
}
func (UnimplementedChannelServiceServer) ListChannels(context.Context, *ListChannelsReq) (*ListChannelsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChannels not implemented")
}
func (UnimplementedChannelServiceServer) GetChannel(context.Context, *GetChannelReq) (*Channel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChannel not implemented")
}
func (UnimplementedChannelServiceServer) UpdateChannel(context.Context, *UpdateChannelReq) (*Channel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChannel not implemented")
}
func (UnimplementedChannelServiceServer) UpdateChannelStatus(context.Context, *UpdateChannelStatusReq) (*Channel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChannelStatus not implemented")
}
func (UnimplementedChannelServiceServer) DeleteChannel(context.Context, *DeleteChannelReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteChannel not implemented")
}
func (UnimplementedChannelServiceServer) DisconnectChannel(context.Context, *DisconnectChannelReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectChannel not implemented")
}
func (UnimplementedChannelServiceServer) SendTestMessage(context.Context, *SendTestMessageReq) (*SendTestMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTestMessage not implemented")
}
func (UnimplementedChannelServiceServer) GetChannelConnectivity(context.Context, *GetChannelConnectivityReq) (*Connectivity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChannelConnectivity not implemented")
}
func (UnimplementedChannelServiceServer) SendMessage(context.Context, *SendMessageReq) (*SendMessageResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChannelServiceServer) mustEmbedUnimplementedChannelServiceServer() {}
func (UnimplementedChannelServiceServer) testEmbeddedByValue()                        {}

// UnsafeChannelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelServiceServer will
// result in compilation errors.
type UnsafeChannelServiceServer interface {
	mustEmbedUnimplementedChannelServiceServer()
}

func RegisterChannelServiceServer(s grpc.ServiceRegistrar, srv ChannelServiceServer) {
	// If the following call pancis, it indicates UnimplementedChannelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChannelService_ServiceDesc, srv)
}

func _ChannelService_ListWanwuAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWanwuAgentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).ListWanwuAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_ListWanwuAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).ListWanwuAgents(ctx, req.(*ListWanwuAgentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_ListWanwuApiKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWanwuApiKeysReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).ListWanwuApiKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_ListWanwuApiKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).ListWanwuApiKeys(ctx, req.(*ListWanwuApiKeysReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_CreateQRLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQRLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).CreateQRLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_CreateQRLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).CreateQRLogin(ctx, req.(*CreateQRLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_GetQRLoginStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQRLoginStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).GetQRLoginStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_GetQRLoginStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).GetQRLoginStatus(ctx, req.(*GetQRLoginStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_CancelQRLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelQRLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).CancelQRLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_CancelQRLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).CancelQRLogin(ctx, req.(*CancelQRLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_CompleteQRLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteQRLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).CompleteQRLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_CompleteQRLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).CompleteQRLogin(ctx, req.(*CompleteQRLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_CreateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChannelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).CreateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_CreateChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).CreateChannel(ctx, req.(*CreateChannelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_ListChannels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChannelsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).ListChannels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_ListChannels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).ListChannels(ctx, req.(*ListChannelsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_GetChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).GetChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_GetChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).GetChannel(ctx, req.(*GetChannelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_UpdateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChannelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).UpdateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_UpdateChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).UpdateChannel(ctx, req.(*UpdateChannelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_UpdateChannelStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChannelStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).UpdateChannelStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_UpdateChannelStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).UpdateChannelStatus(ctx, req.(*UpdateChannelStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_DeleteChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChannelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).DeleteChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_DeleteChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).DeleteChannel(ctx, req.(*DeleteChannelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_DisconnectChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectChannelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).DisconnectChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_DisconnectChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).DisconnectChannel(ctx, req.(*DisconnectChannelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_SendTestMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTestMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).SendTestMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_SendTestMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).SendTestMessage(ctx, req.(*SendTestMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_GetChannelConnectivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelConnectivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).GetChannelConnectivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_GetChannelConnectivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).GetChannelConnectivity(ctx, req.(*GetChannelConnectivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelServiceServer).SendMessage(ctx, req.(*SendMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ChannelService_ServiceDesc is the grpc.ServiceDesc for ChannelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChannelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "channel_service.ChannelService",
	HandlerType: (*ChannelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWanwuAgents",
			Handler:    _ChannelService_ListWanwuAgents_Handler,
		},
		{
			MethodName: "ListWanwuApiKeys",
			Handler:    _ChannelService_ListWanwuApiKeys_Handler,
		},
		{
			MethodName: "CreateQRLogin",
			Handler:    _ChannelService_CreateQRLogin_Handler,
		},
		{
			MethodName: "GetQRLoginStatus",
			Handler:    _ChannelService_GetQRLoginStatus_Handler,
		},
		{
			MethodName: "CancelQRLogin",
			Handler:    _ChannelService_CancelQRLogin_Handler,
		},
		{
			MethodName: "CompleteQRLogin",
			Handler:    _ChannelService_CompleteQRLogin_Handler,
		},
		{
			MethodName: "CreateChannel",
			Handler:    _ChannelService_CreateChannel_Handler,
		},
		{
			MethodName: "ListChannels",
			Handler:    _ChannelService_ListChannels_Handler,
		},
		{
			MethodName: "GetChannel",
			Handler:    _ChannelService_GetChannel_Handler,
		},
		{
			MethodName: "UpdateChannel",
			Handler:    _ChannelService_UpdateChannel_Handler,
		},
		{
			MethodName: "UpdateChannelStatus",
			Handler:    _ChannelService_UpdateChannelStatus_Handler,
		},
		{
			MethodName: "DeleteChannel",
			Handler:    _ChannelService_DeleteChannel_Handler,
		},
		{
			MethodName: "DisconnectChannel",
			Handler:    _ChannelService_DisconnectChannel_Handler,
		},
		{
			MethodName: "SendTestMessage",
			Handler:    _ChannelService_SendTestMessage_Handler,
		},
		{
			MethodName: "GetChannelConnectivity",
			Handler:    _ChannelService_GetChannelConnectivity_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _ChannelService_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/channel-service/channel-service.proto",
}
